<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BookMyHome.Application\BookMyHome.Application.csproj" />
    <ProjectReference Include="..\BookMyHome.Domain\BookMyHome.Domain.csproj" />
    <ProjectReference Include="..\BookMyHome.Persistence\BookMyHome.Persistence.csproj" />
    <ProjectReference Include="..\BookMyHome.Shared\BookMyHome.Shared.csproj" />
  </ItemGroup>

</Project>
