name: BookMyHome_CD

on:
  workflow_run:
    workflows: ["BookMyHome_CI"]
    types: [completed]
    branches: [master]

env:
  IMAGE_NAME: ghcr.io/nicolai-madsen/bookmyhome

jobs:
  publish-image:
    name: Build and push image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}