name: BookMyHome_CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DOTNET_VERSION: "10.0.x"
  SOLUTION_PATH: "BookMyHome.slnx"
  IMAGE_NAME: ghcr.io/nicolai-madsen/bookmyhome

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal

  publish-image:
    name: Build and push image
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get code